# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [12]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

### Step 3. Assign it to a variable called chipo.

In [5]:
chipo = pd.read_csv(url, sep='\t')

### Step 4. How many products cost more than $10.00?

In [6]:
chipo['item_price'] = chipo ['item_price'].apply(lambda x: float(x[1:-1]))

In [8]:
chipo_filtered = chipo.drop_duplicates(['item_name','quantity','choice_description'])

In [19]:
product_price = chipo_filtered[chipo_filtered.quantity == 1]

In [24]:
product_price[product_price.item_price > 10].item_name.nunique()

25

### Step 5. What is the price of each item? 
###### print a data frame with only three columns item_name choice_description and product_price

In [27]:
prodict_price = chipo_filtered[['item_name','choice_description','item_price']]

In [34]:
product_price.sort_values(by="item_price", ascending=False)

,order_id,quantity,item_name,choice_description,item_price
2610,1035,1,Carnitas Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
3749,1499,1,Carnitas Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
2740,1088,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.89
2804,1114,1,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",11.89
4313,1720,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
...,...,...,...,...,...
53,24,1,Canned Soda,[Sprite],1.09
117,51,1,Canned Soda,[Diet Dr. Pepper],1.09
228,100,1,Canned Soda,[Mountain Dew],1.09
200,89,1,Canned Soda,[Diet Coke],1.09
126,55,1,Canned Soda,[Coca Cola],1.09

### Step 6. Sort by the name of the item

In [39]:
chipo.sort_values(by='item_name')

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered?

### Step 8. How many times was a Veggie Salad Bowl ordered?

### Step 9. How many times did someone order more than one Canned Soda?